### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by MindFlare56** [edvin/tornadofx#1000]
An error happened while I do list.forEachIndexed (second time it happened with the same action on two different pieces of code inside a class: Fragment). The first time it disappeared alone and the second time the same but after a moment ???.

May 25, 2019 9:49:42 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)

![Capture](https://user-images.githubusercontent.com/35500233/58376345-4f303900-7f37-11e9-955a-30402dab86b1.PNG)

**Comment by edvin** [comment]
It sounds like your manipulating an observable list bound to an ui element off of the ui thread. That's a big no-no :) Make sure you manipulate the list on the ui thread, and either use a list iterator or another mechanism so that you don't manipulate the list you are iterating over. You could also make an array of the list elements and iterate over that if you want to use foreachindexed, but you can't rely on the index as you remove from the original list, since obviously the indexes would when you remove elements.

**Comment by MindFlare56** [comment]
Oh, so I just had to use list.observable before manipulating it. 
Thank you... It was all my bad sorry.
