### ISSUE TITLE
stylesheet not found when running from commandline

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#103]
In the tornadofx-samples project in module treeviews execute the command:
````
mvn exec:java -Dexec.mainClass=no.tornado.fxsamples.treeviews.TreeviewKt
````
The application will start up with the following error message and the styles indeed are not loaded.

> May 01, 2016 9:55:17 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "css://no.tornado.fxsamples.treeviews.Styles" not found.

When running it from Intellij it works fine.

**Comment by edvin** [comment]
This seems to be because the exec plugin somehow disables the url handlers. I've updated the treeviews-sample to create a runnable jar, so you can now do:

`mvn package && java -jar target/treeviews-1.0.jar`

I'll look into why the exec plugin disables url handlers, but it's not an issue with TornadoFX per say :)

**Comment by edvin** [comment]
I just added a force-install check so that a special url handler will be installed if the framework detects that type safe stylesheets cannot be loaded :)
