### ISSUE TITLE
Reset Form after close window

### ISSUE THREAD

**Issue by regiswg** [edvin/tornadofx#1060]
Hello!

I am from Brazil and my English is not very good.

When I close the Application and reopen the window my inputs are with the previously entered data.

I was wondering if there is any way to reset everything after closing the window.

Or do I have to do it "by hand"?

**Comment by edvin** [comment]
Yes, you have several options.

1. Use a Fragment instead of a View. This will spawn a new instance of your ViewModel you have (or should have) injected. This will give you default values every time you open a new window with that Fragment.

2. Set a new item value into your ViewModel. This will automatically update any bound fields. Simply do `myViewModel.item = NewModelItem()` in `onDock`.

Your English is very good I think :)

**Comment by regiswg** [comment]
thanks for the quick response...

1. about my english... thanks google translator kkkk...

2. and about the window, i'll use the fragment with inject...

3. and thanks  for the best framework, its a very nice work. Im starting in Kotlin and dev .. so it is a very good help

have a good sunday!
