### ISSUE TITLE
ViewModel commit listeners

### ISSUE THREAD

**Issue by fellahi-ali** [edvin/tornadofx#1066]
Hi, 
I was trying to learn how to use the `ViewModel` and `TableView`, I read through the official guide and saw some code examples and of-course tried things by myself, and what I understood is that we need to use **JavaFX** Properties in our **Domain Objects** and bind them to `ItemViewModel` properties and `TableView` columns, for the changes in the `ItemViewModel` to be reflected on the `TableView` on the fly and that seems cool. But what I don't like about this approach is the need to use **JavaFX** properties in my **Domain Objects**, and wanted my **Domain Model** to be free from any framework and only use Plain Java/Kotlin Objects (aka: **POJO**s & **POKO**s) and I found some [code samples](https://github.com/edvin/tornadofx-samples/blob/master/itemviewmodel/withpojos/src/main/kotlin/no/tornadofx/fxsamples/withpojo/view/itemViewModelWithPojos.kt) in the official repo that shows this pattern, but the problem I found is that when something changes in the `ItemViewModel` we need to call `refresh()` on the `TableView` manually because we lost the observability feature provided by **JavaFX** properties, so I tried to find a way to call `refresh()` programmatically when changes committed to the `ViewModel` and the possible ways I found are either: 

1. Override `onCommit()` method on the `ItemViewModel` and call `refresh()`, which means that the `ItemViewModel` should have a reference to the `TableView` which is bad. or,

2. Use `successFn()` when we call `ViewModel.commit()` which also means that we need to have a reference to the `TableView` wherever we call `commit()` which also bad.

And the "good/clean" solution I wanted is as simple as registering a listener to commits in the `ViewModel` that will be notified every time a successful `commit()` is done, which can be used as follow: 
```
tableview {
    myModel.onCommit { refresh() }
} 
```
Very clean isn't it? Actually I had implemented this using Extensions as shown in [this Gist](https://gist.github.com/fellahi-ali/d7beccd6aaa4fd419aef74e1a928eb83).
If you have any suggestions or other solution it will be appreciated. 
If you find this feature useful, I will glade to submit a pull request for it.

**Comment by edvin** [comment]
If you want to use this pattern, simply emit an event which the TableView can listen to. This way you avoid entangling your domain objects with the UI elements. See EventBus for more info.

However, you need to realize that to get all the benefits of JavaFX/TornadoFX, your domain objects simply need to have observable properties, or you're going to find yourself hacking around like this all over the place. If you want to keep your domain objects clean, just use them as DTO's for the view model domain objects, and embed functionality in them to convert to/from the observable counterpart. Easy, clean and you don't have to fight the UI framework at every turn.

The reason this isn't an issue most of the time, is that the server core would be separated and even run in another JVM, where your "true" domain objects recide. The domain objects in the UI app typically get their data via some kind of remoting (http for example) and should satisfy the requirements of the ui framework instead of the server core.

**Comment by fellahi-ali** [comment]
Thanks @edvin  for the response and advices.

> If you want to use this pattern, simply emit an event which the TableView can listen to.

Actually I didn't get to that chapter (EventBus) yet! I will look at it soon.

> If you want to keep your domain objects clean, just use them as DTO's for the view model domain objects

I first started my solution with this pattern, and created for example a class named `EmployeeFX`
for its **Employee** domain object counterpart, but I what I was concerned about is performance issues in a scenario when I should get a list of all Employees from a database repository to show them in a `TableView` for example, I have to convert them all to FX objects, which make me hesitate from this approach! What is your opinion/suggestions about that?

> The reason this isn't an issue most of the time, is that the server core would be separated and even run in another JVM, where your "true" domain objects recide.

Even in that scenario, my concerns are at the Design and Source Code level, If my software tiers/layers shares the same Domain Types, it would be more maintainable I think!. 
Actually, I'm not very experienced in this area! so maybe I'm missing something, so again any suggestions/clarifications would be very appreciated.
