### ISSUE TITLE
how to get the file path which is in the resources directory

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1074]
follow picture is my project directory picture

![](https://github.com/Stars-One/MyBlogCollection/blob/master/Clipboard_20190917.png?raw=true)

I want to get the `config.properties` path in `MainView`,like this
```
val file = File("config.properties")
```
but now I don't have idea to get the path so that I can't create a file object.

Is there a idea to solve the problem?**relative path)**

**Comment by edvin** [comment]
You can do `this.javaClass.getResourceAsStream("/config.properties")`, but you might want to look into the `resources` helper in TornadoFX instead :)

**Comment by Stars-One** [comment]
Thanks.It work

I get it when use the resources helper.I forget add the `/`...

Following is correct code.
```
val steam = resources.stream("/config.properties")
```
And I have to try the first way you say,your code doesn't need the `/` .And it need a classloader.This is correct code.
```
val stream = javaClass.classLoader.getResourceAsStream("config.properties")
```
**Note:The above code is ok when the code be used in a class file.If it be used in the `MainView.kt` file,it would throw a NullPointException**

By the way,I am reading the code of the tornado example project now.The login example is so hard .And could you add some comment?Thanks!



> You can do `this.javaClass.getResourceAsStream("/config.properties")`, but you might want to look into the `resources` helper in TornadoFX instead :)



> You can do `this.javaClass.getResourceAsStream("/config.properties")`, but you might want to look into the `resources` helper in TornadoFX instead :)

**Comment by edvin** [comment]
My code example works, and you absolutely need the /, since your config.properties is at the root of the classpath, while the View is in com/wan/astcool/view.

There is no need to call javaclass.ClassLoader, since that's what will happen if you call javaClass.getResourcesAsStream.

Infact, the resources helper uses that exact same code:

```kotlin
component.javaClass.getResourceAsStream(resource)
```

Your comment about it being ok when "used in a class file" makes no sense :) MainView.kt is being compiled to byte code just like any other class :)
