### ISSUE TITLE
Block param on openModal()

### ISSUE THREAD

**Issue by regiswg** [edvin/tornadofx#1094]
Hello!

If i set the block param = true in a openModal() the setOnCloseRequest method is not  called. Its a BUG?

![image](https://user-images.githubusercontent.com/37145605/66717496-07a82d80-edb0-11e9-8af5-08bb3e29a2dc.png)

**Comment by edvin** [comment]
No, the bug is in your code - you call openModal() with the block parameter, so nothing more will happen on the UI thread until you close the window. So you basically create the window, show it, then call setOnCloseRequest() once the window has been closed again.

Configure the onCloseRequest earlier, for example within the onDock() callback of the View.

**Comment by regiswg** [comment]
I hope you were not offended because this was not my goal ... And probably the error would be in my code even kkkk I expressed badly!

**Comment by edvin** [comment]
Hehe, no I was not offended at all, not sure where you got that idea from :) Bug reports are most welcome! Did you understand my comment and how to fix your code?

**Comment by regiswg** [comment]
Na verdade não... vc diz no onDock() diretamente na view?

**Comment by edvin** [comment]
Perfect :) Thanks for reporting back! It's important to understand that block will infact block any subsequent code from being executed until the window is closed.
