### ISSUE TITLE
Global messages does not respect application class path

### ISSUE THREAD

**Issue by skwee357** [edvin/tornadofx#1139]
I have my application class reside in the following package `io.moneypin.ui`.
When I define a view named `views.SomeView`, its messages are looked inside `resources/io/moneypin/ui/views/SomeView.properties`

When I define global messages using `Messages.properties` I expect it to be inside `resources/io/moneypin/ui/Messages.properties` but tornadofx looks for it in `resources/Messages.properties`.
Is this the desired behavior?

I'm using 2.0.0-SNAPSHOT, kotlin: 1.3.61 and jvmTarget 11

**Comment by edvin** [comment]
Yes, the property files for the global messages are looked up at the root of the classpath :)

**Comment by skwee357** [comment]
Thanks for the SUPER fast reply!

Do you think it will be more consistent to look for inside the package of the `App`?

**Comment by edvin** [comment]
I believe I opted to put it at the root of the classpath because of "automatic looking in parent bundle" functionality. Messages used in your views might not be a child package of the app class, so there wouldn't be a parent relationship to the global bundle, package-wise. It's just a technicality though, either would have worked fine :)

**Comment by skwee357** [comment]
Thanks for the explanation!
