### ISSUE TITLE
DataGrid not updating when observableList updated

### ISSUE THREAD

**Issue by ben-dent** [edvin/tornadofx#1323]
I have a ```DataGrid``` that is linked to an ```observableList``` called ```data```, which gets updated. When updating the values in this ```observableList```, the ```DataGrid``` is not being updated. I have looked in the documentation for some kind of refresh function as the coupling to the ```observableList``` seems to not be working, but there was nothing.

```kotlin
private var datagrid: DataGrid<Foo> by singleAssign()
private var data = ORIGINAL_VALUE
...
datagrid = datagrid(data) {
    ...
}
...

fun bar() {
    data = NEW_VALUE
}
```

Am I using this wrong?

**Comment by SKeeneCode** [comment]
Hi Ben,

I'm assuming you mean that your data grid is updating when items are added or removed from your `data`, but when you update a some property inside an element of your `data`, the dataview isn't updating?

This is because data controls such as `DataGrid`, `ListView`, `TreeView` will only update when the `ObservableList` backing them fires a `ChangeEvent`. An observable list will fire this event when an item is added or removed but it has no way of _automatically_ knowing whether the contents of its elements have changed.

So you need to explicitly tell your observable list to fire a change event when a property inside is changed. Luckily this is easily done; instead of declaring your observable list like this:

`val data = FXCollections.observableArrayList<Modal>()`

We need to provide a list of what is called `extractors`:

`val data = FXCollections.observableArrayList<Modal> { modal -> arrayOf(modal.someProperty, modal.anotherProperty) }`

Whatever data control which is backed by `data` will now update when `modal.someProperty` or `modal.anotherProperty` has its value changed.

Here is a minimal runnable example for you to play with:

<details><summary>Minimal Example</summary>

<p>

```
import javafx.beans.property.SimpleObjectProperty
import javafx.beans.property.SimpleStringProperty
import javafx.collections.FXCollections
import javafx.scene.paint.Color
import tornadofx.*
import java.util.*

fun main() {
    launch<MyApp>()
}

class MyApp : App(Main::class)

class Modal(name: String = "modalName") {
    val nameProperty = SimpleStringProperty(name)
    val colorProperty = SimpleObjectProperty(Color.WHITE)

    override fun toString(): String {
        return nameProperty.value
    }
}

class MainViewModal : ViewModel() {
    val data = FXCollections.observableArrayList<Modal> { modal -> arrayOf(modal.nameProperty, modal.colorProperty) }

    init {
        data.add(Modal("Hello"))
        data.add(Modal("How"))
        data.add(Modal("Are"))
        data.add(Modal("You"))
    }
}

class Main : View() {

    val viewModal: MainViewModal by inject()

    override val root = vbox {
        datagrid(viewModal.data) {
            cellFormat {
                graphic = vbox {
                    style {
                        backgroundColor += it.colorProperty.value
                    }
                    label(it.nameProperty.value)
                    button("Remove me") {
                        action {
                            viewModal.data.remove(it)
                        }
                    }
                    button("Random name") {
                        action {
                            it.nameProperty.value = UUID.randomUUID().toString().take(4)
                        }
                    }
                    button("Random color") {
                        action {
                            it.colorProperty.value = Color.color(Math.random(), Math.random(), Math.random())
                        }
                    }
                }
            }
        }
        hbox {
            button("add item") {
                action {
                    viewModal.data.add(Modal(UUID.randomUUID().toString().take(4)))
                }
            }
        }
    }

}
```
</p>

</details>

![image](https://user-images.githubusercontent.com/32420836/113482661-82f21900-9454-11eb-82e4-672a0da9b1be.png)

**Comment by ben-dent** [comment]
Thanks Sam for your detailed response! This completely fixed my problem :)
