### ISSUE TITLE
NoSuchMethodException main

### ISSUE THREAD

**Issue by JNissi** [edvin/tornadofx#160]
I'm slowly losing my mind over here. I've tried to create a test application just to see how tornadofx works and I can't get even as far as starting the f*ing application. I tried following the examples in readme and creating a Gradle project, Idea project and generating from the tornadofx-quickstart-archetype. I tried running with Kotlin settings, then after checking some issues here I tried running with java configuration and I even downloaded the plugin and tried the run configuration from there.

Whenever I try to run the application it ends up with:
`Exception in Application constructor
Exception in thread "main" java.lang.NoSuchMethodException: org.pallokorva.MyApp.main([Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1678)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:126)`

Even the quickstart archetype does this, so it shouldn't be my code.

**Comment by edvin** [comment]
I've seen this before when the compiled code is not compatible with the version of TornadoFX you're running with. In other words, it could happen if you compile for one version, then upgrade to a non-binary compatible version and run your app again before you clean and build your project.

Could this be the case? If not, can you post your project so we can take a look at it?

**Comment by edvin** [comment]
Oh, and make sure you've upgraded your version dependency to 1.5.4, OK?

**Comment by JNissi** [comment]
Wise words, thanks. I think this should be in the documentation somewhere(If it's there I've missed it). I updated the project JDK in IDEA project structure settings from 1.7 to 1.8 (java7 to java8), didn't touch anything else and after a rebuild it runs no problem.

**Comment by edvin** [comment]
Thanks for the tip, I'll be sure to include this in the wiki as well :)

@thomasnield This should probably go in the guide also. In case of version upgrades you should always do a full rebuild, and some times IDEA refuses to let go of it's cache, so in some circumstances an IDEA restart is required as well.

**Comment by edvin** [comment]
We just figured out that we introduced a regression in the last release, because we removed the primary/empty constructor in the App class. This caused the "Run View" configuration to stop working. Maybe this was what bit you? We'll release 1.5.5 shortly to result this, along with a new version of the plugin. Apps should run just fine, but ad hoc Views will not run against TornadoFX 1.5.4.

**Comment by thomasnield** [comment]
I missed this note, sorry.  I'll document this especially since I've had this issue on occasion too.

**Comment by jakubgwozdz** [comment]
It's not always a cache problem. IntelliJ says "NoSuchMethodException main" when there are some wiring problems. Always in such cases it's good to go with `mvn clean install ; java -jar target/xxxx.jar` and then you'll be able to see the root cause like

```
Caused by: java.lang.IllegalArgumentException: No delegate field with name 'entries' found
        at tornadofx.PropertiesKt.getProperty(Properties.kt:31)
        at pl.jgwozdz.utils.xmlscan.tornadofx.EntryChooserModel.entriesProperty(EntryChooser.kt:38)
        at pl.jgwozdz.utils.xmlscan.tornadofx.TornadoFXApp.<init>(TornadoFXApp.kt:31)
```

In my case it was because I had this in my model: 
```
class EntryChooserModel() {
    var selectedEntry by property<Element>()
    fun selectedEntryProperty() = getProperty(EntryChooserModel::selectedEntry)

    var entries = FXCollections.observableArrayList<Element>()
    fun entriesProperty() = getProperty(EntryChooserModel::entries)
}
```

changing one line to
```
    var entries by property (FXCollections.observableArrayList<Element>())
```

fixed the problem. But I almost lost my hair over it.

Hope this will help the next poor bastard that runs on "NoSuchMethodException main"

**Comment by edvin** [comment]
Thanks for the info :) If you run into weird problems, always clean and recompile. For version upgrades we try to keep source compatibility, but we some times break binary compatibility so you might run into weird runtime errors unless you recompile everything when you upgrade versions as well.
