### ISSUE TITLE
CheckboxTreeCell doesn't show checkbox on treeview

### ISSUE THREAD

**Issue by bausol** [edvin/tornadofx#189]
I have an treeview declared like this:      
```kotlin
            vbox{
                treeview<Test> {
                    root = CheckBoxTreeItem<Test>(test)
                    root.isExpanded = true
                    cellFactory  = CheckBoxTreeCell.forTreeView()
                    cellFormat { text = it.name }
                    populate {
                        it.value.children
                    }
                }
            }

data class Test(val name: String, val children: List<Test>? = null)

val test = Test("Test",
    listOf(Test("Test1"), Test("Test2"))
)
``` 

The problem is that checkbox will not be shown in the treeview. It looks like a normal treeview without checkboxes.

**Comment by edvin** [comment]
The reason for this is that `cellFormat` installs it's own `cellFactory`, so the one you set before is overwritten. I was about to tell you to change `cellFormat` to `cellDecorator` when I realized we haven't added a cell decorator for TreeView yet. I will create it this evening and get back to you :)

In the mean time you can remove the `cellFormat` call and override `toString` in your Test class to get the same effect, if that's an option for you.

**Comment by edvin** [comment]
Just a quick checkin - the procedure used to support `cellDecorator` for `ListView` and `TableView` doesn't seem to work for `TreeView`, probably because it is not data driven like those controls. I see the callbacks happen, but the changes are not applied for some reason. I will have to investigate further, but at least you should have a workaround for now.

**Comment by edvin** [comment]
I've found a better way to implement this now, by providing a complete proxy of the Cell, and forwarding the updateItem call to the `cellDecorator` function. I'm heading into surgery tomorrow morning but I should be back on my feet, literally, within a day or two so I can commit a better solution to this.

**Comment by edvin** [comment]
I've investigated this further, and the Cell/TreeCell class is simply not proxyable due to final and private classes, so for your use case you should instead either create your checkbox in `cellFormat` or provide a custom CellFactory/Cell if you don't want to just change the toString() og your Item.
