### ISSUE TITLE
Vertical Grow support for VBox Constraints

### ISSUE THREAD

**Issue by gtnarg** [edvin/tornadofx#190]
When using controls such as TextArea in a form, the form does not honor vertical growth as configured below:

```
form {
    fieldset { 
        field {
            textarea {
                vboxConstraints { Priority.ALWAYS }
            }
        }
    }
}
```

**Comment by edvin** [comment]
The container for the textarea in the example above is an `hbox`, that's why the `vboxConstraints` have no effect. We will look for a way to express this by other means.

**Comment by edvin** [comment]
By the way, for your example above to have any effect you need to specify the vGrow property:

```kotlin
vboxConstraints {
    vGrow = Priority.ALWAYS
}
```

**Comment by edvin** [comment]
I've been thinking more about this. As mentioned, the `field` builder creates an `HBox` container and places all the children inside it. What if we introduced a `verticalField` that creates a `VBox`? That would place multiple inputs below each other, and also support `vgrow`. We could reuse the existing `field` builder and add a `orentation` to it, but the problem is that the op block would then need to operate on `Pane` instead of either `HBox` and `VBox`, so you would have to do a cast to access `fillWidth`, `fillHeight` and other properties of the boxes.

Another approach would be to create a new container called `XBox`, which has all the properties of `HBox` and `VBox`, and lays out its children according to the `orientation`. With this we could actually keep backwards compatibility. Not sure how hard it would be to do though.

**Comment by edvin** [comment]
I have added `orientation` as a parameter to each field, so you can now do:

```
form {
    fieldset { 
        field(orientation = VERTICAL) {
            textarea {
                vgrow = Priority.ALWAYS
            }
        }
    }
}
```

Is this satisfactory for you?

**Comment by gtnarg** [comment]
The following only grows the bottom field when the window is resized:

```
import javafx.geometry.Orientation
import tornadofx.View
import tornadofx.*
import javafx.scene.layout.Priority

class Issue190 : View("My View") {

    override val root = form {
        fieldset("FieldSet") {
            field("Field 1") {
                textarea {
                    prefRowCount = 2
                    mnemonicTarget()
                    vgrow = Priority.ALWAYS
                }
            }

            field("Field 2", Orientation.VERTICAL) {
                textarea {
                    vgrow = Priority.ALWAYS
                }
            }
        }
    }
}
```
![image](https://cloud.githubusercontent.com/assets/1252704/22183306/fe590998-e088-11e6-870e-e3f12c1b48f1.png)

**Comment by edvin** [comment]
Yes, because you didn't add the `Orientation.VERTICAL` parameter to the first field, so it's created as an `HBox`. Does that make sense?

**Comment by gtnarg** [comment]
Doh! Makes perfect sense. Works great now :)

Thanks Edvin

**Comment by edvin** [comment]
Great! Thanks for bringing this up :) It made the Form component much more versatile :)
