### ISSUE TITLE
i18n  don`t work , What was wrong with me?

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#218]
<img width="940" alt="qq20161222-0 2x" src="https://cloud.githubusercontent.com/assets/22107668/21417986/3d7d7728-c859-11e6-9a84-8116c6ccef57.png">

**Comment by edvin** [comment]
Maven will not copy arbitrary resources from the src-folders to the build folder, so you have two choices.

1. Alter your Maven configuration to include .properties files in the build
2. Move your property file to `src/main/resources/com/iezview/osgi/view/MainView.properties`

Option 2 is best IMO, since you don't need to alter the default Maven configuration.

**Comment by QingMings** [comment]
Thankyou , it`s ok .
