### ISSUE TITLE
FXML not found when present

### ISSUE THREAD

**Issue by primetoxinz** [edvin/tornadofx#222]
In attempting to use FXML, tornadofx 1.5.8 cannot seem to find the fxml file although it is definitely present

[here](https://gist.github.com/primetoxinz/c06ad82b93fd401f799a5db7d9abce05) is the code I tried to use and the crash log accompanied with it.

for unknown reasons the classloader can't find the file I guess?

**Comment by edvin** [comment]
Your FXML file is called `Test.xml`, while the correct name would be `Test.fxml`. Also, if you're using Maven you must remember that Maven doesn't copy arbitrary resources from the source folder to the target folder, so you must make sure you either configure Maven to include `**/*.fxml` or put the FXML files in `src/main/resources` instead of `src/main/java`.

Your first error is the file name, and if it doesn't help to correct it, check the file location as described above.

**Comment by primetoxinz** [comment]
Oh, the naming issue was just a typo when uploading to gist, but I am using gradle which would also require it in the resources folder, completely slipped my mind

**Comment by primetoxinz** [comment]
yep, moving to src/main/resources fixed it, thanks!

**Comment by edvin** [comment]
You're welcome :)
