### ISSUE TITLE
Support for Nested FXMLs

### ISSUE THREAD

**Issue by wooky** [edvin/tornadofx#243]
It doesn't look to me like TornadoFX supports nesting FXML files very well. For example, I have these two files:

Inside.fxml
```
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.control.Button?>

<Button fx:id="myButton" text="Hello" xmlns="http://javafx.com/javafx/8.0.60" xmlns:fx="http://javafx.com/fxml/1" />
```

Outside.fxml
```
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.layout.VBox?>

<VBox xmlns="http://javafx.com/javafx/8.0.60" xmlns:fx="http://javafx.com/fxml/1">
   <children>
      <fx:include source="Inside.fxml" fx:id="inside" />
   </children>
</VBox>
```

test.kt
```
import javafx.scene.control.Button
import javafx.scene.layout.VBox
import tornadofx.View

class Outside: View() {
    override val root: VBox by fxml()
    val insideController: Inside by inject()
}

class Inside: View() {
    override val root: Button by fxml(hasControllerAttribute = true)
    val myButton: Button by fxid()
}
```

Running this will cause a runtime exception "no controller specified", possibly because JavaFX is expecting Inside.fxml to have an fx:controller set.

If I add `fx:controller="Inside"` to the button and set Inside's root's delegate to `fxml(hasControllerAttribute = true)`, it runs fine, but I have no way of interacting with the button. If I were to add to Outside
```
init {
    insideController.myButton.text = "Testing"
}
```
it wouldn't do anything. For some reason it thinks the value never gets set to anything meaningful. So am I missing something or is there just no support currently for nesting FXML files?

**Comment by edvin** [comment]
You are correct, there is currently no support for nested controllers. If you add `fx:controller` to an included FXML file, it would instantiate it's own version of that controller, and the one you `inject` would not be the same instance.

I will investigate if we can support this neatly and get back to you ASAP.

**Comment by edvin** [comment]
This will be hard to do right without creating a custom FXMLLoader. That's a huge undertaking, I estimate almost a week of work to get it right. It has an added bonus though, we would not need the `hasControllerAttribute` anymore, but I'm unsure if it's worth it, considering how powerful the builders are and that most people seem to use builders instead of FXML for TornadoFX apps.

I would recommend not using a custom controller for the included file, and letting the main view control the include as well. If that's not good for your use case, you can just use a normal class as the sub controller, and let it register itself with the view controller when it's instantiated. That would be pretty easy to do, but is not really an elegant solution. If you can use that approach, I'd be happy to write an example for you.

As it stands right now, I don't think I can start working on a custom FXMLLoader at the moment, as other features and documentation is more important to finish IMO.

**Comment by wooky** [comment]
The only reason I'm using FXML is because I'm using Scene Builder for my programs. If I were writing GUI code by hand, then I'd most likely use the TornadoFX builders as well.

It doesn't appear that you can't include an FXML file without specifying the controller, as I mentioned in the first post. If I were to tell it that the controller is the same as the one used by the Outside file, then that would defeat the whole purpose of including files within files.

I'm going to try another solution, and that's turning my Inside file into a control. Maybe that'll work.

**Comment by edvin** [comment]
I just got another idea, this might be possible after all. I will try and let you know :)

**Comment by edvin** [comment]
It seems like I've found a way to support this, under these requirements:

1. The nested root element shouldn't have an `fx:id` attribute if the controller is a UIComponent. You don't need to either, since it's available as the `root` property of the UIComponent.

2. To get to `insideController` you would need to do `val insideController: Inside by fxid()` - i.e use the `fx:id` instead of inject. Inject would work if what you inject is a `View`, but to get to the same instance for a Fragment you would have to use `fxid()`.

3. `hasControllerAttribute` is no longer needed.

This looks promising right now, but I need to test more before I can commit this.

**Comment by edvin** [comment]
Unfortunately there were pitfalls with this approach as well, and I was forced to revert the changes. We have however decided to investigate creating our own FXMLLoader which would make it trivial to support this.

In the mean time I think you're far better off with creating one FXML file per View, and nesting them together via builders instead of `fx:include`. The FXML files would stay exactly like you have them except for the include.

```
class Outside : View() {
    override val root: VBox() by fxml()
    init {
        root.add(Inside::class)
    }
}

class Inside: View() {
    override val root: Button by fxml()
    val myButton: Button by fxid()
}
```

No need to specify the controller attribute unless you want to, and you can remove the include from `Outside.fxml`.

Quite frankly I don't see much of a disadvantage to this approach at all. Please let me know if this doesn't work for you.
