### ISSUE TITLE
menuitem doesn't respond on the first click

### ISSUE THREAD

**Issue by nekonenene** [edvin/tornadofx#259]
Hello, @edvin. I'm creating a sample application using TornadoFX.
( https://github.com/nekonenene/TornadoMemo )

And I found a strange behavior of menuitem.

```kotlin
class MenuBarView: View() {

    override val root = menubar {
        menu("Test") {
            menuitem("Item1") {
                setOnAction {
                    println("Item1 pushed!")
                }
            }
        }
    }
}
```

I expected appear the message when clicked "Item1". But, the console did not display the message, then I clicked "Item1" again, the message appeared.

So, I had to write as follows instead...

```kotlin
class MenuBarView: View() {

    override val root = menubar {
        menu("Test") {
            menuitem("Item1")
                .setOnAction {
                    println("Item1 pushed!")
                }
        }
    }
}
```

This code works I expected. Is this problem a bug of TornadoFX?

Thanks for your consider and nice framework.

**Comment by edvin** [comment]
Hi! The `menuitem` builder expects the action as it's code block parameter, so what you're doing is actually calling `setOnAction` on the first click.

Option 1 is to remove the `setOnAction` wrapper:

```kotlin
menuitem("Item1") {
    println("Item1 pushed!")
}
```

Option 2 is to use the `item` builder, which we introduced after we realized that the `menuitem` builder behaves differently than every other builder in the framework (!). The `item` builder operates on the menuitem as you would expect:

```kotlin
item("Item1") {
    setOnAction {
        println("Item1 pushed!")
    }
}
```

The unfortunate oversight in the creation of the `menuitem` builder has led to a bit of confusion. Some find it very handy since they mostly just specify an action and feel that the `setOnAction` call just becomes boilerplate, but it is sure confusing. I think we will deprecate the `menuitem` builder in favor of the `item` builder somewhere down the line.

**Comment by nekonenene** [comment]
Wow, very great answer!!

Thanks a lot. I got completely. The listener of `menuitem` sets the listener of it, haha.
I'll try to use `item` instead of `menuitem` right now, and close this issue. Thank you very much! 👼

**Comment by edvin** [comment]
Great to hear. And sorry about the confusion :)

**Comment by nekonenene** [comment]
I have just finished creating the sample application that using TornadoFX!!
https://github.com/nekonenene/TornadoMemo

Thanks a lot for your support.

**Comment by edvin** [comment]
Great to hear. I took at look at your code and it looks very clean :) I just want to show you a couple of shortcuts you can use in `MainView.kt`. This is the original file:

```kotlin

class MainView: View("TornadoMemo") {
    private val mainController: MainController by inject()
    val menuBarView: MenuBarView by inject()
    val textAreaView: TextAreaView by inject()
    val footerView: FooterView by inject()

    override val root = borderpane {
        top = menuBarView.root
        center = textAreaView.root
        bottom = footerView.root
    }

    init {
        titleProperty.bind(Bindings.concat(Constant.APP_NAME, ModelManager.fileModel.mainWindowTitleProperty))
    }
}
```

It can be written like this:

```kotlin

class MainView: View("TornadoMemo") {
    override val root = borderpane {
        top(MenuBarView::class)
        center(TextAreaView::class)
        bottom(FooterView::class)
    }

    init {
        titleProperty.bind(Bindings.concat(Constant.APP_NAME, ModelManager.fileModel.mainWindowTitleProperty))
    }
}
```

**Comment by nekonenene** [comment]
Wow, fantastic!!
It's very simple and beautiful.

Thank you edvin! I love you!

**Comment by edvin** [comment]
You're welcome. Thanks for your feedback, it means a lot :)
