### ISSUE TITLE
Revenge of the component binding

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#266]
While using the new bindComponent feature I encountered a problem where I can't figure out whats going wrong. The binding seems to be broken when using a `SortedList` as new items are not displayed when added to the underlying list.

See the updated gist for example: https://gist.github.com/dominiks/efe2c9b886a6cdc6ff914cfdb951ea0f

When adding a new item it should appear in the `left` and `right` but it actually only shows up in the list that is not sorted.

Is this usage error on my part concerning the sorted list?

**Comment by edvin** [comment]
I think the problem is your sorting expression :) It doesn't take into account that any of the values passed to it can be null. Try changing the sorting expression to something defensive like:

```kotlin
projectList.sorted { a, b -> a?.name?.compareTo(b?.name?:"") ?: 0 }
```

The reason I suspect this is this commend on SortedList:

**Note: invalid SortedList (as a result of broken comparison) doesn't send any notification to listeners on becoming valid again.**

Does that solve it?

**Comment by dominiks** [comment]
That did not solve the issue. The sorting expression does not even get called.

**Comment by edvin** [comment]
I just ran your code against 1.7.0 and it works fine, but with one caveat: If you create a new project without a name, the comparison fails, and the left pane stops adding components. If you always add projects with a name, it works perfectly for me. I made zero adjustments to your code.

If you want to keep accepting projects without a name you need to update the sorting expression though.

Since it's obviously not working for you we need to look elsewhere for a solution. What we're doing here is actually just adding elements to an observable list, and it doesn't look like that list is firing events when stuff is added. Can you try to agument the sample by assigning the sortedlist to a val and adding an `onChange` listener to it to see if that is triggered when you add an element?

**Comment by edvin** [comment]
Update: It seems to fail in some circumstances. A couple of adds are ok, then it stops, and not always on the same operation, even given the exact same input values. I'd like to create a test case that excludes the ui to see if the there is a problem with the sorted list.

**Comment by dominiks** [comment]
I have just updated the gist with a comparator object and tried it again, but the result stays the same. For reference this is on win64 Java 1.8.0_121.

**Comment by edvin** [comment]
I tried this:

```kotlin
        left {
            SortedList(projectList, comparator).onChange {
                println("Sorted list changed: $it")
            }
            projectList.onChange {
                println("Project list changed: $it")
            }
        }
```

It gives different output every time. Some times the sorted list receives a single change event, other times it gets none. Output after adding two elements in one go was:

```bash
Sorted list changed: { [com.example.demo.view.Project@3e97ca53] added at 0 }
Project list changed: { [com.example.demo.view.Project@3e97ca53] added at 0 }
Project list changed: { [com.example.demo.view.Project@4d5e97db] added at 1 }
```

The sorted list just doesn't receive all change events.

Then I changed it slightly:

```kotlin
        left {
            val sortedlist = SortedList(projectList, comparator)
            vbox(5.0).bindComponents(sortedlist, ::ProjectFragment)
            projectList.onChange {
                println("Project list changed: $it - sorted list is $sortedlist)")
            }
        }
```

Now it works perfectly. It seems that if I just poke the sortedlist, it will update. Just calling `size` on it seems to do the trick:

```kotlin
left {
    val sortedlist = SortedList(projectList, comparator)
    vbox(5.0).bindComponents(sortedlist, ::ProjectFragment)
    projectList.onChange {
        sortedlist.size
    }
}
```

Looks like a bug in SortedList to me.

**Comment by edvin** [comment]
Haha, it was stearing me right in the face.. The reason it started working when I accessed the `sortedlist` inside the onChange callback is that it prevented it from being garbage collected. Simply make the sorted list a field member and you should be good:

```kotlin
class ProjectListView() : View() {
    val projectList = FXCollections.observableArrayList<Project>()
    val sortedList = SortedList(projectList, comparator)

    override val root = borderpane {
        left {
            vbox(5.0).bindComponents(sortedList, ::ProjectFragment)
        }

        right {
            vbox(5.0).bindComponents(projectList, ::ProjectFragment)
        }

        bottom {
            button("New Project").setOnAction {
                val fragment = ProjectFormFragment()
                fragment.openModal(block = true)
                projectList.add(fragment.result)
            }
        }
    }
}
```

The reason is that `bindComponents` uses a weak reference to the list, to play nice in case the list is no longer used. Maybe that was a mistake, I did it to prevent memory leaks. In any case, making it a field member should be a solid solution. Can you confirm this solves it for you?

**Comment by dominiks** [comment]
Yep, I made it a field member to try calling `size` on the sorted list after adding and that worked. Removed the `size` call and it still worked. 

Though I agree with the decision to use a weak reference - bindings love to create subtle memory leaks that are hard to find or get rid off.

**Comment by edvin** [comment]
Great! This was a good exercise, now we know :) Can we close the issue?

**Comment by dominiks** [comment]
Yes, thanks for your help.

**Comment by edvin** [comment]
You're most welcome. This was a learning experience for me as well.
