### ISSUE TITLE
DataGridSelectionModel reworking

### ISSUE THREAD

**Issue by bvolkmer** [edvin/tornadofx#285]
Hey,
I just worked with the SelectionModel of a DataGrid. (Adding a android like long press behavior. Open element on short press, enter selection/modify mode after long press)

At first. The whole thing is pretty undocumented.

Also, the most methods take the indices as arguments. I think this is unintuitive, as you have just the Object f.e. in `cellCache`. So you'll always first need a `this@datagrid.items.indexOf(it)`.

And at last is the `clearSelection(index: Int)` misleading, and should be better `unselect` to have a contrast to clearing all selections.

I'll make a pull request in the next days, if you think like me.
Greetings,

**Comment by edvin** [comment]
The `DataGridSelectionModel` simply implements `MultipleSelectionModel` and overrides all of it's methods. There is no need to document those, as they are documented in `MultipleSelectionModel` and it's super class `SelectionModel`. You can't rename `clearSelection`, since it's part of the `SelectionModel` API in JavaFX.

The methods in the selection model is mostly called by the framework itself, that's why they work on indicies for the most part. 

Inside the `cellCache` callback you are passed the current item as the single parameter. You also have access to `selectedItem` and can call methods on the `selectionModel`, like for example `selectionModel.select(item)`.

I don't think I understand what you feel you're missing here, maybe you can show me a code example with the problematic code?

Support for long press etc would be most welcome though :) I'm waiting on a Surface Pro I ordered and was planning to add it myself, but if you beat me to it that's just great :)

**Comment by X4fyr** [comment]
Ah. I haven't seen the implementation. Somehow intellij/gradle does not download the source/docs, why I just looked at the github repo. `selectionModel.select(item)` is the only method to accept the item.
I think then there isn't much to do. I experienced the whole thing as unintuitive.

I just cloned the repo and insert the long press behaviour I have by now.

**Comment by edvin** [comment]
Would you be willing to share your longpress/touch implementation?

**Comment by X4fyr** [comment]
#286

**Comment by edvin** [comment]
Thanks for the PR, closing this issue and will continue in the PR.
