### ISSUE TITLE
plusAssign unexpected behaviour for TabPane

### ISSUE THREAD

**Issue by Xfel** [edvin/tornadofx#294]
If using the plusAssign operator to add a UIComponent to a TabPane, the behaviour is confusing.
First of all, while it does set the title of the tab correctly, it does not bind it, so later updates to the title of the UIComponent will not be reflected.
Also, it does not respect the UIComponent's closeable property.

**Comment by edvin** [comment]
Hi! I've committed a fix that makes sure the `textProperty` of the Tab is bound to the `titleProperty`, and the `closeableProperty` of the Tab is bound to the `closeable` property of the `UIComponent`. Instead of plussAssign, you can also use `add(view)` or now also `tab(view)` or even `tab(view::class)`.

I added a first class `closeable` property to `UIComponent` so you can configure the state like this:

```kotlin
override val closeable = SimpleBooleanProperty(false)
```

I added a declarative option to say the same:

```kotlin
disableClose()
```

Here is a small test app that demonstrates the new usage:

```kotlin
class TabPaneTest : View("TabPane Test") {
    override val root = tabpane {
        tab(TabOne::class)
    }
}

/**
 * Check that the tab title updates when the input changes.
 * The Tab should not be closeable as it binds to the closeable property.
 */
class TabOne : View("Tab One") {
    override val root = textfield(titleProperty)
    override val closeable = SimpleBooleanProperty(false)
}
```

You can configure the default closeable state for views via the `Workspace.defaultCloseable` boolean.

Does this work as you expected?

**Comment by Xfel** [comment]
Wow, that was quick! 
Yes , that is working now. Thank you!

**Comment by edvin** [comment]
Sweet! Thanks for reporting this. Can we close the issue?

**Comment by Xfel** [comment]
Yep
