### ISSUE TITLE
Issue with TableView and Bindings?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#30]
Hey is there an issue with using `Binding` for mapped properties in a `TableView`? I am using RxJavaFX and an extension method to turn an `Observable` into a `Binding`. 

```kotlin
class MyClass {
    val description = attributes.map { it.desc }.toBinding()
}
```

When I declare a `TableView<MyClass>`  and map to the `Binding`, I am getting the result of `toString()` on the `Binding` object. 

```kotlin
column("Description",MyClass::description)
```

**Comment by edvin** [comment]
What type is attributes?

**Comment by thomasnield** [comment]
`String`

**Comment by thomasnield** [comment]
Oh wait, `attributes` is an `Observable<MyDomainObject>` using a custom class I use. That shouldn't matter though because I'm mapping to a `String` before it goes into a `Binding`.

**Comment by edvin** [comment]
Ah, I see the problem. Since description is a Binding<String> and hence also a ObservableValue<String> the property reference `MyClass::description` only matches this column function in the FXTableView class:

`fun <T> column(title: String, prop: KProperty1<S, T>): TableColumn<S, T>`

The only column function we have right now that supports observable values is the one that reference a function that returns an observable:

`inline fun <reified T> column(title: String, observableFn: KFunction<ObjectProperty<T>>): TableColumn<S, T>`

We would need one that supports `KProperty1<S, ObservableValue<T>` or something.

Need to walk the dog and put my daughter to bed, then I'll see about adding one or changing one of the existing ones :)

**Comment by edvin** [comment]
Hmm.. it seems it can't be done, because KProperty<S, T> has the same type erasure as KProperty<S, ObservableValue<T>>. Need to think of a workaround.

**Comment by thomasnield** [comment]
No rush : ) There's always that alternative mapping means with the functional argument if it gets cumbersome.

**Comment by edvin** [comment]
Found one possible route: Adding @JvmName(name = "columnForObservable") to the new column declaration. I'll check it in, so you can try while I put the kid to bed, OK?

**Comment by edvin** [comment]
Checked in! See how it goes, back in 15 :)

**Comment by edvin** [comment]
It seems to work for me, what about you?

**Comment by thomasnield** [comment]
Sorry, was out for lunch with coworkers. Let me try it...

**Comment by thomasnield** [comment]
Darn firewalls... one moment.

**Comment by thomasnield** [comment]
I think that worked!

**Comment by edvin** [comment]
Nice :)

**Comment by thomasnield** [comment]
Btw, one more thought. I advise we leave in that other means to map a value to a column for those rare occasions where a Property is returned from a function and not a _property_ property. 


```kotlin
 categories.subscribe { cat ->
                    column<BigDecimal>(cat) { it.value.sumForCategory(cat) }
                }
```

**Comment by thomasnield** [comment]
I refactored my `TableView` to use the new column mapping conventions (except for that function one). Everythings looks good!

**Comment by edvin** [comment]
Great! Yeah, we should keep the others as well.
