### ISSUE TITLE
No style builder for MenuItem

### ISSUE THREAD

**Issue by HaasJona** [edvin/tornadofx#327]
I'm trying to do this:

            tableview.contextmenu {
                val selectedItems = tableview.selectionModel.selectedItems
                for (action in actions) {
                    item(action.name) {
                        action {
                            action.run(selectedItems)
                        }
                        if(action.isDefault) {
                            style { fontWeight=FontWeight.BOLD }
                        }
                    }.also {
                        it.enableWhen { action.isEnabledFor(selectedItems) }
                    }
                }
            }

It does compile, but the style{} is applied to the whole tableview. The `style()` extension method should probably apply to `Styleable`, not `Node`.

Workaround:

                            style = InlineCss().apply { fontWeight=FontWeight.BOLD }.render()

**Comment by edvin** [comment]
Good catch! It wasn't completely trivial to solve, since `Styleable` doesn't define a `setStyle()` function. I moved the `style` builder onto `Styleable` as you suggested, but had to provide a setter function inside it which retrieves the actual setter from known subclasses. We might need to expand the list of supported subclasses in the future.
