### ISSUE TITLE
ViewModel.dirty is set when the underlying model changes

### ISSUE THREAD

**Issue by TheJhonny007** [edvin/tornadofx#358]
The following code shows, that the dirty property is set, even though the model and viewModel are identical. This happens, when the original model is being updated from another location. Either the dirty flag shouldn't be set when the underlying model is changed or the ViewModel shouldn't update it's own properties and set itself as dirty.

Code:
```kotlin
class Pet(name: String) {
	val nameProperty = SimpleStringProperty(name)
	var name: String by nameProperty
}

class PetModel(var pet: Pet): ViewModel() {
	val name = bind { pet.nameProperty }
}

fun main(args: Array<String>) {
	val model = Pet("Roger")
	val viewModel = PetModel(model)

	viewModel.dirty.addListener {_, _, isDirty ->
		println("Is dirty: $isDirty")
		println("Pet value: ${model.name}")
		println("ViewModel value: ${viewModel.name.value}")
	}

	model.name = "Fluffy" 	//update the original model
}
```

Output:

	Is dirty: true			//ViewModel appears to be dirty
	Model value: Fluffy		//Models name is Fluffy
	ViewModel value: Fluffy 	//ViewModels name is Fluffy aswell

**Comment by edvin** [comment]
Thanks for reporting and also for including a reproducible test case :) I have modified the dirtyListener so that it doesn't marks the model dirty when an external change is made:

```kotlin
val sourceValue = propertyMap[property]!!.invoke()?.value
if (sourceValue == newValue) {
    dirtyProperties.remove(property)
} else if (!autocommitProperties.contains(property) && !dirtyProperties.contains(property)) {
    dirtyProperties.add(property)
}
```

Just to be clear, this represents a behavioral change we should at the very least document here. Say a user is editing some data in a form, and he has a save button which is only available when the model is dirty. Now, an external change to the underlying model is performed, but the user doesn't see an option to save the modified object. It is now the responsibility of the developer to save that change when it is made to the underlying model.

I'm not saying this is wrong or should be addressed somehow, but it's worth mentioning.

**Comment by TheJhonny007** [comment]
Yeah, I think that needs to be documented, although if you edit data in a form, while the underlying model is being externally modified you see the changes in the form and any modifications of the ViewModel by the user are being overridden anyways. So it probably is obvious (to the user), that the underlying data has been modified.

**Comment by edvin** [comment]
Yeah, this is a minor issue, but it would be nice to have the behavior documented. Maybe you want to take your newly added write access for a spin and add it? 😁
