### ISSUE TITLE
Add support for custom Nodes

### ISSUE THREAD

**Issue by PvdBerg1998** [edvin/tornadofx#367]
TornadoFX does not support using custom Nodes instead of the default ones. For example: JFoenix adds several custom Nodes like the `JFXButton`. I ended up writing several wrappers like this one:
```Kotlin
fun EventTarget.jfxButton(text: String = "", graphic: Node? = null, op: (JFXButton.() -> Unit)? = null): JFXButton
{
    val button = JFXButton(text)
    if (graphic != null) button.graphic = graphic
    return opcr(this, button, op)
}
```

Maybe change all the builders to something like this:
```Kotlin
fun EventTarget.button(
        text: String = "",
        graphic: Node? = null,
        buttonFactory: (String) -> Button = { Button(it) },
        op: (Button.() -> Unit)? = null
): Button
{
    val button = buttonFactory(text)
    if (graphic != null) button.graphic = graphic
    return opcr(this, button, op)
}
```

So the builders can be used like this:
```Kotlin
button(buttonFactory = { JFXButton(it) }) { 
        // ...
}    
```

**Comment by t-boom** [comment]
I don't think that's a good solution.

1. Many libraries also include custom nodes that wouldn't make sense as a factory for an existing builder (such as the JFXRippler or JFXHamburger)
2. Those custom nodes often have extra properties/functionality that would not be accessible from the builder in your example
3. It's a much bigger pain to type `button("Some Text", buttonFactory = { JFXButton(it) }) { ... }` instead of `jfxButton("Some Text")`
4. This is a rare/edge case that comes from interacting with specific libraries

I think a better solution would be to just have small wrapper libraries for this and other such libraries (JFXtras, ControlsFX, etc.). You could then just include a tornadofx.jfoenix library and have all the extensions you need without polluting TornadoFX core.

**Comment by edvin** [comment]
I agree, a wrapper library for that specific component suite is really the way to go. There might be a case for adding builder interceptors to the framework in a slightly more generic way, but it has several drawbacks as @t-boom pointed out.

**Comment by PvdBerg1998** [comment]
You've convinced me. Mind if I create a pull request with my extensions when I have finished them?

**Comment by edvin** [comment]
I think they are better suited to live in a separate library, so we don't pull in a dependency on JFoenix in TornadoFX Core. Maybe you'd want to host that project yourself? If not, I can create an empty repo for it and you can push to that?

**Comment by PvdBerg1998** [comment]
I can host it myself, that's not a problem. Thanks for the quick replies!

**Comment by edvin** [comment]
Please let us know about the URL for the project once you have published it! Very interesting :) Also, let us know if you run into trouble with the approach :)

**Comment by t-boom** [comment]
I get the feeling there will be a lot of these kind of wrapper libraries around eventually for all the different JavaFX custom controls libraries. Good to see it underway :)
