### ISSUE TITLE
Drawer refreshes to wrong item when the app window looses focus and gets it again

### ISSUE THREAD

**Issue by DrFornax** [edvin/tornadofx#463]
I have a problem with the drawer on Mac OS. Tested with TornadoFX 1.7.12-SNAPSHOT and 1.7.11.

> override val root = drawer {
>         item<View1>(expanded = true)
>         item<View2>()
>         item<View3>()
> }

When I open the View2 or View3 item of the Drawer, go to an other application and go back to the current View item, it switches back to the View1.

Steps to reproduce:

- Have a drawer with multiple items and make the first expanded=true
- Click on one of the drawers that are not expanded
- Click into a different window (IntelliJ IDEA for example)
- Go back to the TornafoFX App and click somewhere inside the view of the current item
--> The view switches back to the default view

The same problem occurs when you have different screens and move the app from one screen to another screen and then click inside the view. It will switch to the default item.

Thank you for your help

**Comment by edvin** [comment]
I’m not able to reproduce. Please attach a small test case if you can :)

**Comment by edvin** [comment]
As we discussed on slack - this is not a bug, it was simply due to that you had enabled live reloading of views, which will effectively load a new instance of the view every time you focus the app, hence the ui state is lost. This is by design, and only an issue when debugging with live views enabled.
