### ISSUE TITLE
How to use the ">" symbol in Kotlin's css

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#531]
Hi, I'm trying to pass this class, but I do not know how to represent the symbol ">" to kotlin.
```
.jfx-list-cell:odd:selected > .jfx-rippler > StackPane,
.jfx-list-cell:even:selected > .jfx-rippler > StackPane {
    -fx-background-color: rgba(0.0, 0.0, 255.0, 0.2);
}
```
Any example of how to pass it to a kotlin class?

**Comment by edvin** [comment]
Use the `child` infix function:

```kotlin
someClass child someOtherClass
```

**Comment by TioCoding** [comment]
Thanks for the reply, I'm trying to pass the CSS I wrote above, but I found a problem in the StackPane:

```
jfxListCell {
  and(odd, even){
     and(selected child jfxRippler child StackPane){ // Erro message: Classifier 'StackPane' does not have a companion object, and thus must be initialized here
          backgroundColor += c(0, 0, 255, 0.2);
     }
  }
}
```

**Comment by edvin** [comment]
There is no `StackPane` CSS Element class defined in TornadoFX by default. This is to avoid confusion between the JavaFX Node classes and the CSS Element classes. When you write StackPane above, you'll see that you have actually imported and referenced `javafx.scene.layout.StackPane`, which is obviously not what you wanted.

If we were to add `StackPane` as a CSS Element by default, people would start importing the Stylesheet CSS Element definition when they wanted a `StackPane` instead of the Node subclass. The confusion goes both ways as you can see.

The pragmatic approach was simply to not define them as CSS Elements, but provide a construct that allows you to define these if needed. For some strange reason, JavaFX doesn't define a css class for StackPane, ala `.stackpane`, but rely on element definitions instead. To define a css element you do:

```kotlin
val StackPane by csselement()
```

Now you can use it just like you use css classes, but it renders as `StackPane` instead of `.stackpane` since it's not a CSS class.

**Comment by TioCoding** [comment]
Thanks, I'm good enough. :smile:
