### ISSUE TITLE
Wizard not reusable

### ISSUE THREAD

**Issue by freelon** [edvin/tornadofx#540]
Hello there,
I'm currently using the Wizard, but I couldn't find a way to properly reset it, in case the user wants to run it again. I'm calling 
```
find<CustomerWizard> {
    customer.item = Customer()
    onComplete {
        println("Wizard finished with customer ${customer.item}")
    }
    openModal()
}
```
The problem is, once I ran the wizard, if I run above code again, the wizard is still on the last page (with a clean new `Customer` though). When I click Finish in the second run, `onComplete {}` is not run again.

It would be great to have the wizard being reusable (or if it somehow is, sorry, then I'd like to know how ;) )

BR 
Johannes

**Comment by edvin** [comment]
You can probably do `wizard.currentPage = wizard.pages.first()` to go to the first page, but the Wizard is not intended to be reused. Why don't you simply start a new one in the same scope?

**Comment by freelon** [comment]
Sorry, I was under the impression the wizard should be used as singleton (since in the guide it is also referenced using `find<Wizard>`. Just creating a new one of course works, thanks.

Just in case I missed something there as well (a bit off topic): as you see I initialize the CustomerView with a new Customer. If I don't do that I don't get any error because of a missing backing object, just of course later I don't get a `Customer` object. So, is just initializing the Customer() at that point the preferred way to do it?

Thanks in any case
JOhannes

**Comment by edvin** [comment]
`find` will create a new instance of `Fragment`, or locate the existing instance of a `View` in the current scope, so that's fine :)

How you stuff a Customer into the model is a matter of preference really, you could even put one into the ViewModel by default:

```kotlin
class CustomerModel : ItemViewModel<Customer>(Customer())
```

That might actually be a good idea to do by default in examples etc as well, so that people don't get confused as to why they don't get an item in the ViewModel when they commit :)

**Comment by freelon** [comment]
OK, great, thanks :)
