### ISSUE TITLE
SmartResize.Policy manual resize broken

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#570]
As of 1.7.11 resizing a column with the mouse moves the left edge of the column instead of the edge that is actually clicked on. Can be reproduced in `ExpandableTableTest`

**Comment by edvin** [comment]
The bug was actually introduced https://github.com/edvin/tornadofx/commit/f4bb3bdea2147d0814a33dc279a0023e50dd89a9https://github.com/edvin/tornadofx/commit/f4bb3bdea2147d0814a33dc279a0023e50dd89a9 - @tieskedh, I don't see what goes wrong here directly, but will try to backtrack and figure out what changed to affect the resize behavior.

**Comment by edvin** [comment]
While looking for bugs, I found one in the `width` override for `TornadoFXTreeTableColumn`. It set the `maxWidth` instead of the `prefWidth` property. That doesn't affect this case of course.

**Comment by edvin** [comment]
The delta for the right column seems to be positive instead of negative when dragging any column header to the left.

**Comment by edvin** [comment]
The next bug I found was in this line:

```kotlin
val colIndex = param.table.contentColumns.indexOf(paramColumn)
```

This always returned -1 now, since the new column wrappers didn't implement equal/hashCode functions. This hm.. changed the behavior, but still no cigar.

**Comment by edvin** [comment]
Committed the fix :)
