### ISSUE TITLE
SortedFilteredList disables table sorting

### ISSUE THREAD

**Issue by nihiluis** [edvin/tornadofx#605]
Normally, if you click on a table column header you can change the Ordering of the table rows. If you use a SortedFilteredList instead of an ObservableArrayList, this feature breaks.

Is there a way to fix this?

**Comment by edvin** [comment]
It sounds like a comparator issue. Can you try to call `yourSortedFilteredList.bindTo(yourTable)` to see if that resolves it? This should be taken care of automatically, so if that does indeed solve your problem, please post an example that illustrates the bug so I can figure out why it isn't configured automatically.

**Comment by nihiluis** [comment]
That fixed it. Thank you!

I think this is the gist of it. Do you need something more specific?

View
```Kotlin
override val root = vbox {
...
table = tableview {
                hide()

                column("ID", Model::id)
                column("Name", Model::name)
                column("Description", Model::description)

                onDoubleClick {
                    onDoubleClick(selectedItem)
                }

                columnResizePolicy = SmartResize.POLICY

                setRowFactory { getRowFactory() }

                controller.yourSortedFilteredList.bindTo(this)
                items = controller.yourSortedFilteredList
            }
...
```
Controller
```Kotlin
    val yourSortedFilteredList = SortedFilteredList<Model>()
init {
        val initialPredicate = l@ { item: Model ->
            return@l true
        }

        systemTargets.predicate = initialPredicate
        clientTargets.predicate = initialPredicate
        componentTargets.predicate = initialPredicate

        filterText.textProperty().addListener { _, _, newValue ->
            val data = yourSortedFilterList

            data?.predicate = l@ { item ->
                if (newValue == null || newValue.isEmpty()) {
                    return@l true
                }

                val lowerCaseFilter = newValue.toLowerCase()
                if (item.name.value.toLowerCase().contains(lowerCaseFilter)) {
                    return@l true
                }

                false
            }

            data?.refilter()
        }
    }
```

**Comment by edvin** [comment]
That tableview declaration wouldn't compile now, because you're missing a type declaration, so I suspect you removed something from your running code. In any case, try this instead:

```kotlin
table = tableview(controller.yourSortedFilteredList) {
                hide()

                column("ID", Model::id)
                column("Name", Model::name)
                column("Description", Model::description)

                onDoubleClick {
                    onDoubleClick(selectedItem)
                }

                smartResize()

                setRowFactory { getRowFactory() }
            }
```

Bottom line: Pass your sorted filtered list into the tableview builder and it should work out of the box. I will look at an improvements so manual items assign works as well, but that's just extra boiler plate :)

**Comment by edvin** [comment]
For others reading this - the issue was that assigning to `tableview.items` manually bypasses an important step in setting up the SortedFilteredList. Instead of assigning to `items` you should do one of the following:

1. Pass the sortedFilteredList into the tableview builder: `tableview(mySortedFilteredList)`
2. Call `yourSortedFilteredList.bindTo(yourTable)`

If you go for option no 2 (for example because the TableView was created with FXML), you don't need to assign to `tableview.items` - that is taken care of by `bindTo`
