### ISSUE TITLE
Updating a scrolling text view

### ISSUE THREAD

**Issue by micabytes** [edvin/tornadofx#611]
Only recently fell across tornadofx, but happy to have done so - great to finally find a sane way to build guis in Kotlin desktop apps.

Still working my way through the docs. One thing I'm still wondering on is how to best build dynamic GUIs with text.

E.g., I have a ScrollPane containing TextFlow objects some of which may be clickable. Clicking on those objects may change the text in the model - which should of course lead to the ScrollPane getting updated/refreshed.

Obviously, I can update the view by discarding the old View and inserting a new one (using replaceWith). Are there other ways of achieving the same thing? Any samples/examples I may have overlooked?

**Comment by edvin** [comment]
If I understand you correctly, the text can change, so that the TextFlow might consist of wastly different nodes after the change is applied. You don't necessarily need to replace the whole view, but you probably do have to remove all the nodes in your flow and repopulate them. There is not much help from the framework itself for this, but you might take inspiration from how `bindChildren` is implemented, to make a nice reusable function for it.

**Comment by micabytes** [comment]
Ok, thanks - saved me from spending time looking for that.

I'm partial to Android's adapter pattern myself, but for the moment I'm just building a simple sample app, so will probably just do it the easy way.
