### ISSUE TITLE
EventBus not work with child view 

### ISSUE THREAD

**Issue by orochies** [edvin/tornadofx#640]
when I define a subscription in a daughter view the subscription is not released.

```
object MyEvent : FXEvent()

class MainView : View("")

override val root = VBox () {
this += ChildView()
}

}

class ChildView : View("") {
init {
subscribe<MyEvent > {
// this not work, not fire after invoke fire() method from MainView
}
}
```

Thanks

**Comment by edvin** [comment]
This happens because you manually instantiate the ChildView. You must never instantiate a UI Component manually. Either use `inject`, `find`, or `add`. Simply changing `this += ChildView()` to `add<ChildView>()` resolves the issue.

There are a number of other issues with your code, here is a cleaned up sample with best practices.

```kotlin
object MyEvent : FXEvent()

class MainView : View() {
    override val root = vbox {
        add<ChildView>()
        button("Fire").action { fire(MyEvent) }
    }

}

class ChildView : View() {
    override val root = label("Waiting...") {
        subscribe<MyEvent> {
            text = "Event was fired at ${LocalDateTime.now()}"
        }
    }
}
```

**Comment by orochies** [comment]
Thanks, that work for me, but how send params to ViewChild?

I need pass viewmodel to ViewChild and currently do it by constructor.

**Comment by gtnarg** [comment]
Read up on Scopes in the documentation.  They allow you to do just this without requiring parameter passing.
