### ISSUE TITLE
Inline CSS color  properties are not working 

### ISSUE THREAD

**Issue by WiseNN** [edvin/tornadofx#658]
- When copying the example code,  I get an error:
<img width="619" alt="screen shot 2018-03-04 at 5 10 20 pm" src="https://user-images.githubusercontent.com/17106171/36951222-0f598f02-1fcf-11e8-8c2a-c6b73e448987.png">

<br />
- Also, when I change the append operator function to an equal operator, I get an error:
<img width="548" alt="screen shot 2018-03-04 at 5 12 49 pm" src="https://user-images.githubusercontent.com/17106171/36951245-4db543e0-1fcf-11e8-8e52-34df7a48f6e0.png">

It says there is a <b>type mismatch, and asks for a: MultiValue<Paint> object, but Found: Color</b>

Is there any way to fix this? I also do not know what a MultiValue<Paint> object is. Can someone fix this?

**Comment by edvin** [comment]
`backgroundColor` accepts multiple colors, so even if you only want to specify one you need to use the `+=` syntax from your first screenshot. As you can see, it's perfectly valid.

For the `textFill` attribute I suspect you have imported the wrong `Color`, class - probably the one from Swing instead of JavaFX.

**Comment by ruckustboom** [comment]
I think this can be closed...
