### ISSUE TITLE
Q: What is workspace property in Component class?

### ISSUE THREAD

**Issue by Awais16** [edvin/tornadofx#682]
Hi,
I wonder what workspace property is for in component class?
If it is a reference to the parent Workspace then we can access this in children views or subclasses of Workspace? 
for example
`workspace.tabContainer.tabs.size` was never set even in Workspace child class.

**Comment by edvin** [comment]
You can access the workspace property provided that the view is already docked in a Workspace. The workspace property will therefore only be populated after `onDock` is called in a View that is actually docked in a Workspace. The tabcontainer will only be active if you have configured tab mode for the workspace.

**Comment by Awais16** [comment]
My subclass
```
class MainView: Workspace(messages["mainview.title"],NavigationMode.Tabs) {
  init{
     dock<HomeView>()
   }
}
```

and the view 
```
class HomeView : View("Home") {

    override fun onDock() {
        super.onDock()
        println(workspace.tabContainer.tabs.size)
    }

}
```

workspace property were always default or never set the size is always zero in HomeView class as well as in MainView class if accessed with workspace property. But `this.tabContainer.tabs.size` in MainView is working fine.

**Comment by edvin** [comment]
Ah, I see. If you start your app from IDEA by using MainView as the app entrypoint, it works, but if you use a workspaceapp which references MainView, it fails. I will have a look!

**Comment by edvin** [comment]
Do you by any chance bootstrap your app using the WorkspaceApp class, like this?

```kotlin
class MyApp : WorkspaceApp(MainView::class)
```

Try changing it to:

```kotlin
class MyApp : App(MainView::class)
```

And see if that resolves the issue. Since you have created your own subclass of Workspace you should not use the `WorkspaceApp` boot method.

**Comment by edvin** [comment]
I've added a warning log message to catch this mistake. Let me know if it resolves the issue for you :)

**Comment by Awais16** [comment]
Nope I am extending it from App
`class MyApp: App(SigninView::class, Styles::class)`
and after successful login I am opening MainView using
`replaceWith(MainView::class)`
🤔 ❔

**Comment by edvin** [comment]
Can you post a working/complete sample, since I'm not able to reproduce the error when the app is started the right way? :)

**Comment by Awais16** [comment]
here is a quick sample [Link](https://github.com/Awais16/bugtorn)
in TestView1.kt
`workspace.dock(TestView2(),true)` 
should work when TestView1 is docked? and what about find(DemoWorkspace::class).dock()?
moreover in DemoWorkspace as well 
`workspace.dock(TestView1(),true)` doesn't work which is because its in init block? but docks works fine.

How can we close a fragment when it is opened using opendialog or window?

Thanks

**Comment by edvin** [comment]
No, you must never instantiate UIComponents yourself. Either use `inject` or `find`, or any of the overloads that accepts an `UIComponent` as a parameter. You've made this same mistake all over your code.

Every component has a default workspace unless you instantiate a spesific one. When you do dock on your components, they dock in a workspace that isn't visible to you because you just instantiated a class that happens to be a workspace instead.

Furthermore, a Fragment is not a singleton, so doing `find(TestView2::class).close()` doesn't achieve what you want - it will instead instantiate a new TestView2 instance and call close on it, before it has ever been used or shown.

Fix all the mistakes pertaining to what I mentioned above, then configure that you want to use `DemoView` as your default workspace:

```kotlin
class MyApp: App(Signin::class, Styles::class){
    override fun start(stage: Stage) {
        FX.defaultWorkspace = DemoWorkspace::class
        super.start(stage)
        stage.isMaximized = true
    }
}
```

 Then you can swap the login view for the current workspace using this code:

```kotlin
button("login"){
    action {
        replaceWith(workspace)
    }
}
```

When the workspace is initialized, it should dock the default view by referencing the view type:

```kotlin
class DemoWorkspace : Workspace("Hello Workspace") {

    init {
        dock<TestView1>()
      ...
```

If you want to open TestView2 in a separate window and then close it later, you must save the created TestView2 instance so you can call close on it:

```kotlin
                button("open"){
                    action {
                        val tw2 = TestView2()
                        tw2.openWindow()
                        val timeout= PauseTransition(3.0.seconds)
                        timeout.setOnFinished {
                            tw2.close()
                        }
                        timeout.playFromStart()
                    }
                }
```

I hope these tips will get you going :)

**Comment by Awais16** [comment]
Thanks, seems like I was missing FX.defaultWorkspace and 
importantly: 
> you must never instantiate UIComponents yourself

👍

**Comment by edvin** [comment]
Yeah, those were the most important issues for sure :) Now, the `workspace` property of any View will reference that Workspace instance.

**Comment by Awais16** [comment]
yes its working in all docked views now. 
Moreover I was calling a Views/fragment .close() and the primarystage was minimized. It's resolved as well by using inject View instead of instantiated one. Thanks 👍 

I think I will start contributing to Kitchensink's (runnable jar links are broken) with small details related to components or application flow. :)

**Comment by edvin** [comment]
Thanks, that would be perfect - I don't have much time these days myself to improve the samples so any help would be great!
