### ISSUE TITLE
Popup example

### ISSUE THREAD

**Issue by yay** [edvin/tornadofx#683]
[This document](https://github.com/edvin/tornadofx/wiki/Components) says

```
For popups or other short lived objects, you might consider Fragments instead.
```

but gives no examples. There is `openWindow`, but nothing like `openPopup` or `showPopup` in `tornadofx/Component.kt`.

What would be the right way to create a popup in TornadoFx?

What I'm trying to do is to essentially have a borderless window that shows (without changing focus) on mouse enter, hides on mouse leave and follows the mouse on mouse move. I almost got there with regular windows, but the `without changing focus` part is tricky and, if I understand correctly, the Popup would solve this.

**Comment by edvin** [comment]
An actual popup is created with the `tooltip` builder in TornadoFX :) What I meant in the documentation is that for windows you open and throw away after some user input, a Fragment is a better option than a View in many cases, since they won't retain state when you open another Fragment of the same type later (since they are separate instances as opposed to View which is a singleton within it's scope).

**Comment by yay** [comment]
I've been just trying to use the `tooltip` builder instead, passing my graphic node (chart) to it, but it looks like it's not possible to control (remove) the show/hide delay with this approach in Java 8: https://bugs.openjdk.java.net/browse/JDK-8090477

**Comment by edvin** [comment]
Bummer. Then you're probably left with having to control all the mouse events yourself and show/hide a Fragment or View I think.

**Comment by yay** [comment]
Indeed. Oh well, you gotta to what you gotta do. Thanks for your response.
