### ISSUE TITLE
View navigation outside views

### ISSUE THREAD

**Issue by LimmaPaulus** [edvin/tornadofx#729]
Hi!
replaceWith() is very convenient to use for changing views, but I found it bad habit to handle navigation in view-layer. Would it be possible to do something like this in viewModel/controller/presenter

`navigationService.showView(MainView::class)`

Where navigationService would be some class or interface easy to construct and inject.

**Comment by edvin** [comment]
When you extend the `View` class, you should think of it as a ViewController. It's a good place to do navigation IMO, but you can surely do the same from a controller, no problem. Your proposed function call will only work with a single stage though, for example the primaryStage, but that is probably fine for your use case since you dreamed up that function signature :)

If you feel you gain anything from it you can use the following example as a base for a navigation service:

```kotlin
class NavigationService : Controller() {
    inline fun <reified T : View> showView() =
        FX.primaryStage.uiComponent<UIComponent>()?.replaceWith(T::class)

}

class View1 : View("View1") {
    val navigationService: NavigationService by inject()

    override val root = stackpane {
        setPrefSize(300.0, 200.0)
        button("Goto View 2").action {
            navigationService.showView<View2>()
        }
    }
}

class View2 : View("View2") {
    override val root = stackpane {
        label("I'm View2")
    }
}
```

If you want to support several stages you could send in the current View as a parameter, and your navigation service could find it's stage via the `root` property.

**Comment by LimmaPaulus** [comment]
Thanks! That seems prominent, I will try it.

I come with C#/WPF background, and I'm used to think View as a thin markup-layer with single ViewModel to handle all ui-logic and routing to services etc. 

Let's suppose that I have a button which should do a database query and then show new view with data from query as parameters. If I must handle navigation in View, I would be forced todo also database query in view. I don't think it would be good programming style. I can't call ViewModel to do query and then change view, because I don't want to change it if execution fails.

I don't mean that your approach with ViewController is bad, but at least I'm used to different style. If you really want that TordanoFX supports varying styles of architectures, I would recommend you to create some official navigation service with easy way to pass parameters. Based on my experience, navigation is often a big problem when trying to implement MVVM.

**Comment by edvin** [comment]
I'm not sure why you concluded you have to do both the database query and the navigation in the View, but you certainly don't have to :)

 ```kotlin
button("Go").action {
    runAsync {
        dbService.getData()
    } ui { data ->
        // Open new View and pass data as parameters or better yet, put it in a new scope for the
        // new View to find
    }
}
```

If `dbService.getData()` fails, an error dialog is shown with the stack trace. If you want to handle it more explicitly, add a `fail { }` block to `runAsync`.

TornadoFX is not forcing this or any other programming style, you can do whatever you want, even do all this from a controller. The controller however needs to know about what View to replace with the new, since the View could be present in any number of open stages (windows). If your app is a single window app, you don't need to pass the view, as you can just replace the view of `FX.primaryStage` as I showed in the first example.

TornadoFX _has_ easy ways to pass parameters, both directly as you open views, but more importantly through scopes. Read up on this in the guide, you'll see that this style of navigation is easy to do, and don't need a navigation service to support (All you is just call thisView.replaceWith(thatView). If you feel you need a few utility functions to support this, just make them - and if you feel they would be beneficial to others, submit a PR :)

**Comment by LimmaPaulus** [comment]
Sorry, I was a bit unclear. Of course I don't have to execute actual database query in view, but I have to call some service to do that. The code you wrote is exactly the thing that I don't want to do in View: switch to background thread, call service, set fetched data to properties, show and hide progress bar, handle errors - I can't find way to do any of this outside view if I must handle navigation after operation in View. Or at least I find it very odd to do this part of logic in View if all other logic is in ViewModel/Controller.

But I understand the problem with multiple windows. I'm very beginner with JavaFX/TornadoFX and maybe how a bit wrong mindset.

I can't think that my way of thinking role of View is rare, but of course feel free to discard the idea of more official NavigationService. I'm personally happy now as I know how to call find() and replaceWith() statically via FX-class :).

Current way to pass parameters is also satisfying, I didn't mean that TornadoFX would not have such. Scope-thing left a bit mysterious for me even though I have read section about it multiple times from guide.

And thanks for this great library! I really think that it is revolutionary way to create GUI-applications :)

**Comment by edvin** [comment]
If it doesn't fit with your programming style to place navigation code in the View controller (which the View subclass should be thought about as), then there is absolutely nothing wrong with putting navigation in a separate controller or a view model. TornadoFX doesn't care how you do it. I want TornadoFX to cater for as many patterns as possible without forcing any of those patterns on you, so I think a navigation service would just send the wrong signal and not provide much benefit.

The `replaceWith` function can be used from anywhere you have access to a View anyways, and there really isn't much more to it than calling that function. Not sure I see an issue with using the programming style you want, that's it :) Maybe if you could show me a complete example and point me to where you feel the problem is?

**Comment by LimmaPaulus** [comment]
Yep, but I don't want to hold reference to View in ViewModel. That's why I needed a static way to call navigation functions.

**Comment by edvin** [comment]
You don't need to hold a reference, just pass the view in. You either must do that, or you must keep track of your open stages somehow. This is no different in any other UI toolkit or library - if you open several windows you need to know which one to put the new view into.

**Comment by LimmaPaulus** [comment]
> You don't need to hold a reference, just pass the view in

Could you clarify a bit. I don't want to see reference to View in ViewModel. What do you mean by passing the view in? I don't see difference it this context between keeping reference in property or passing it as parameter to single function.

**Comment by edvin** [comment]
You said "hold a reference" and that is avoided by passing the view you want to replace into the function that should ultimately replace the view. Any framework that helps you navigate to another page must know what window to replace the view in, there is no way around it. Somewhere you need to register what window the "navigation service" should operate on. So I ask you - how do you do this normally? And then just do it the same way in TornadoFX if that's what you feel is right :) Again, if you're just used to working on a single window, it's just as easy to do this in TornadoFX, just do `FX.primaryStage.uiComponent<UIComponent>().replaceWith<NewView>()`. If you use that pattern a lot, just create a function so you can do `navigateTo<NewView>().

**Comment by LimmaPaulus** [comment]
I'm maybe more used to work with more static windows, where the entire view doesn't change to another. But I'm satisfied now and have no problems any longer, thanks.

**Comment by edvin** [comment]
OK, great. If you have "areas" that change, you could create a service that controls that area, so you'd say `mainAreaController.showView<NewView>()` perhaps :) Either that, or `navigationService.showView<NewView>(MAIN_AREA`, where `MAIN_AREA` is an enum defined in the navigation service.

**Comment by LimmaPaulus** [comment]
OK, thanks for great advice :)
