### ISSUE TITLE
Only one open internal window

### ISSUE THREAD

**Issue by Applemann** [edvin/tornadofx#746]
Hello I am now new in TornadoFX and I am playing with it now and trying some examples.
Now I am testing some examples with Fragments:
```
import javafx.stage.StageStyle
import tornadofx.*


class MyView : View() {
    override val root = vbox {
        setMinSize(800.0, 600.0)
        button("Press Me") {
            action {
                find<MyFragment>().openWindow(stageStyle = StageStyle.UTILITY)
                //openInternalWindow<MyFragment>(modal = false)
            }
        }
    }
}

class MyFragment: Fragment() {
    override val root = label("This is a popup")
}
```
this code can open more new windows.
And when I add line for open internal window:
```
openInternalWindow<MyFragment>(modal = false)
```
instead of `openWindow()`   it open one internal window..

but when I press button more than one so internal window is still only one.
Is somewhere some problem or you support only one opening internal window??
Do you will support opening more internal windows than only one??

Thanks

**Comment by lewismorgan** [comment]
There can only be one internal window. It's rendered onto the active scene, so you'd probably need to create a new Scene and assign it to the fragment if you want more than one internal window, but you can still only have one scene per stage, which is why it works for openWindow. If you're wanting an MDI based interface there are much better alternatives than an internal window like tab containers.

**Comment by Applemann** [comment]
@lewismorgan Yes I am aiming for MDI based interface..
Thank you very much for so fast response and I will go to look for the tabpane or containers..;)
