### ISSUE TITLE
JDK 10 and beyond

### ISSUE THREAD

**Issue by abhinayagarwal** [edvin/tornadofx#794]
Running master on JDK 10. Here are some issues which I am not sure how to proceed with or need feedback on my current approach. Therefore, I am writing them here to discuss:

**1. ApplicationListener.kt**

Uses reflection to fetch on `com.sun.javafx.application.PlatformImpl`'s `initialized` variable. 

```
val initializedField = PlatformImpl::class.java.getDeclaredField("initialized")
```
My inexperience with osgi tells me we can replace `PlatformImpl` with:

```
Class.forName("com.sun.javafx.application.PlatformImpl").getDeclaredField("initialized")
```

But I do not like this solution. @edvin Does [`Platform#startup`](https://docs.oracle.com/javase/10/docs/api/javafx/application/Platform.html#startup(java.lang.Runnable)) help somehow?

**2. AutoCompleteComboBoxSkin.kt**

`init { }` sets an event handler for mouse click event on `arrowButton`. This node was previously `protected`.

```
arrowButton.setOnMouseClicked {
    if (isShowing) {
        resetFilter()
    }
}
```

I am hoping we could get rid of this code without any implications?

**3. ItemControls.kt**

`DirtyDecoratingTableRowSkin` and `ExpandableTableRowSkin` cannot extend from `TableRowSkin` because of a Kotlin Bug: https://youtrack.jetbrains.com/issue/KT-12255

Our best approach here is to create public Java class for these and let TornadoFX use them. I am open to any other alternative.

**4. SqueezeBox.kt**

`SqueezeBoxSkin` has the following code in `init { }`. The overridden `handleControlPropertyChanged` simply calls `super.handleControlPropertyChanged` (BehaviorSkinBase) which is actually a no-op.

```
protected void handleControlPropertyChanged(String propertyReference) {
    // no-op
}
```
So, may be we can simply remove the init block?

**5. Reflection**

For any other API which has been either changed to private or package-private, I am going to fallback to reflection. This can be discussed in the PR.

**6. Separate branch for JDK10 and beyond**

I would have been much happier if we could keep the same master for developing both JDK8 and JDK10+. This would have been possible if there was no inheritance. Since most uses of skin has a package change, I don't think we could somehow make this possible. If someone has a better plan, now is the time to comment :)

**Comment by edvin** [comment]
Thanks for taking the initiative to drive the JDK10 support forward!

1. It seems we could call `Platform#startup` and catch `IllegalStateException` to determine if the Application Thread is initialized. It's a bit of a hack, but this is for a special case to support OSGi apps and not a big deal IMO.

2. We can still get to the `arrowButton` by finding the child with id `"arrow-button"` it seems :)

3. Yeah, let's to that. I had to resort to this solution in the past in a couple of areas. It doesn't create any problems other than that we need to compile java code as well. No big deal!

4. Let's kill the no-op init block :)

5. Using reflection lets us stay feature complete instead of removing features. We might need to add `--add-exports java.base/sun.reflect=ALL-UNNAMED` though. Let's go with reflection and simply document the features that would require `add-exports` to work.

6. I see no way around a branch, but I think we should eventually have the JDK10+ version as the master branch, and a separate branch for JDK8 where we can backport fixes and selected features. I'm open to other suggestions as well!

**Comment by abhinayagarwal** [comment]
Making TornadoFX modular is not in the scope of this issue because of the various external factors involved.

**Comment by ctadlock** [comment]
Closing
