### ISSUE TITLE
Strange Behaviors with tabpane

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#8]
I'm getting some odd behaviors with the tabpane, and I might be using it incorrectly. 

```
nadofx.*

class MainApp : App() {
    override val primaryView = MainView::class

    class MainView : View() {
        override val root = VBox()

        init {
            with(root) {
                tabpane {
                    tab("Report") {
                        hbox {
                            this += Button("Hello 1")
                        }
                    }
                    tab("Data Entry") {
                        hbox {
                            this += Button("Hello 2")
                        }
                    }
                }
            }
        }
    }
}

```

Whatever controls I add to a tab, they are visible on all tabs. Can you validate if I'm doing something incorrectly?

**Comment by edvin** [comment]
`Tab` is unfortunately not a `Pane`, so it doesn't have the `hbox` builder. What's happening is that `hbox` is called on `root`, since it is the first parent `Pane`.

I see that this is confusing, and for it to work correctly, I would need to extend builder support specifically for `Tab`. (Duplicate the extension functions).

Workaround for now is to create the HBox inside the tab like this:

```kotlin
content = HBox().apply { 
    button("Hello 1")
}
```

PS: There is a builder for button, no need to use `this += Button` :)

**Comment by thomasnield** [comment]
Oh yeah, forgot about that regarding button, thanks! I think that `apply()` will work for me for now. But yeah its slightly counter-intuitive.

**Comment by edvin** [comment]
I need to check if it is possible to end up using the "wrong import", so you would still get the behavior above if you import "hbox for Pane" instead of "hbox for Tab". In that case I think it might be worth breaking backwards compatibility and doing something different for tab, like for example:

```kotlin
// Instantiate content pane and then operate on that instead
tab("Report", HBox()) {
    // This button is added to the HBox
    button("Hello 1")
}
```

// If you would need to configure the tab further, you could do:

```kotlin
with (reportTab) {
    // do work here
}
```

Alternatively, the tab builder could take two functions, the first operate on the content container and the second on the tab:

```kotlin
tab("Report", HBox(), {
    // This button is added to the HBox
    button("Hello 1")
}, {
    // Here you configure the tab instance
})
```

**Comment by edvin** [comment]
A fix to avoid this confusing behavior is now available in head. It actually felt quite nice to use, and there is zero chance of confusion :)

**Comment by thomasnield** [comment]
Awesome, I'll check it out later today. Thanks Edvin!

**Comment by edvin** [comment]
No problem @thomasnield - thanks for the valuable feedback :)

**Comment by thomasnield** [comment]
Used JitPack to pull that commit in as a dependency. Works great! Thanks.

**Comment by edvin** [comment]
Cool! Didn't know about JitPack, that's pretty sweet!

**Comment by thomasnield** [comment]
It is handy, especially for rapidly developing projects. This is all I did.

```
repositories {
  mavenCentral()
  maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.edvin:tornadofx:master-SNAPSHOT'
    //compile 'no.tornado:fx:1.2.+'

    testCompile 'junit:junit:4.12'
}
```
