### ISSUE TITLE
ViewModel does not allow binding to properties of nullable type

### ISSUE THREAD

**Issue by NLBuescher** [edvin/tornadofx#848]
given the following objects:

```kotlin
class Entity {
    val nullableLongProperty = SimpleObjectProperty<Long?>(null)
    var nullableLong: Long? by nullableLongProperty
    
}

class EntityModel : ItemViewModel<Entity>() {
    var nullableLong = bind { item?.nullableLongProperty }
}
```

I get "Type inference failed: Cannot infer type parameter T" in `EntityModel`. This happens because in the `bind` function, `T` is defined to be a subtype of `Any`, rather than `Any?` (`<reified T : Any>`).

If I change it to:

```kotlin
…
val nullableLongProperty = SimpleObjectProperty<Long>(null)
…
```

and remove the explicit nullablility, it works fine, but it doesn't reflect the type that I'm actually working with.

Is there anything to be done about this, or is this just a quirk of the Java interoperability that we'll just have to live with?

**Comment by edvin** [comment]
Nullable properties are supported using the new/preferred binding syntax:

```kotlin
val nullableLong = bind(Entity::nullableLongProperty)
```

**Comment by NLBuescher** [comment]
That works perfectly, thanks!

**Comment by edvin** [comment]
You're most welcome. If you find places in the guide or other documents using the old syntax, feel free to submit a PR or let us know about it :)

**Comment by mdres** [comment]
@edvin Maybe I am doing it wrong, but some usecases cannot be expressed like this. We want to bind a property of a property in our ViewModel, and I think the right way to do this is:

        bind { item?.myCoolMember?.observable(CoolType::nestedProp) }

However that does not compile, because the property producer lambda must return a Property<Any>, not a Property<Any?>. I can cast it and it works fine at runtime (in fact, the bindMutableNullableField overload does exactly that as well internally), but it would be nice if it was part of the API so we dont need an ugly cast.

**Comment by edvin** [comment]
Try using the `select` function to create a nested binding :)

**Comment by mdres** [comment]
@edvin Thanks for the suggestion. However, a simple select does not support rollback/commit, and if i try to bind() the selected property I am back to the original problem, because bind does not accept nullable properties. Or am I doing something wrong?
