### ISSUE TITLE
Programmatically focus on an element

### ISSUE THREAD

**Issue by Defman21** [edvin/tornadofx#919]
Is it possible to do something like `findById(Styles.myId).focus()`? I'd want to change focus on a text input after a specific action.

**Comment by edvin** [comment]
JavaFX has a built in method for looking up nodes called `lookup`, and TornadoFX has added a `select` function based on this functionality to support type safe stylesheets. You must make sure to call `select` on an ancestor of the node you're looking for. Since TornadoFX cannot know what type of Node you try to find, you have to supply a type hint as well:

```kotlin
select<Label>(Styles.myid).requestFocus()
```

**Comment by Defman21** [comment]
It works, thanks! :)
