### ISSUE TITLE
togglePseudoClass does not work

### ISSUE THREAD

**Issue by Mosch0512** [edvin/tornadofx#998]
I am divining an csspseudoclass:
```kotlin
val testPseudoClass by csspseudoclass()
```
And than i am trying to use it here. But it seams like it does not work:
```kotlin
togglePseudoClass(Styles.testPseudoClass.name, simpleBooleanProperty.get())
```
But if i use this one it seems to work as expected...
```kotlin
toggleClass(Styles.testPseudoClass , simpleBooleanProperty)
```

I think togglePseudoClass does acctualy what it should in this case but the method needs overloadings like the toggleClass i think so.

**Comment by Mosch0512** [comment]
mybe setting togglePseudoClass deprecated because toggleClass is supporting pseudoclasses anyway?

**Comment by edvin** [comment]
I assume that by the very little descriptive "does not work", you mean that it doesn't compile, since there is no overload for `togglePseudoClass` that accepts an observable property? :)

Edit: You edited your post to add `simpleBooleanProperty.get()`, so now your second statement both compiles and should work.

As you discovered, `toggleClass()` supports the combination of type safe style, observable properties and psuedo classes, so that's the way to go. The `togglePseudoClass(string, boolean)` is needed if you don't use type safe css and want to toggle a psuedo class :)

**Comment by Mosch0512** [comment]
ahhh yehar but why are there no overloads for the togglePseudoClass too? 
For me as a newbie to this project i was a little bit confused if using toggleClass is the way to go ^^

**Comment by edvin** [comment]
It's simple - for Type Safe CSS we have no need to specify that it's a pseudo class, since it's already expressed in the type safe css class :) So for type safe css you can always use `toggleClass`, no need for an overload. I know that can seem confusing at first, but if you think about it, adding a `togglePseudoClass` call for type safe css is just bloat really :)

**Comment by Mosch0512** [comment]
I got the point makes sense :+1: 

Thx :)
